--[[
	******************************************************************************
	* @name			:	valve
	* @authors		:	Cod2rDude
	* @date			:	January 12 2025
	* @lastEdit		:	January 15 2025
	* @brief		:	A library for limiting rate of tasks.
	* @version		:	1.7.5
	******************************************************************************
	* @attention
	*
	* Copyright © 2026 Axon Corporation.
	* All rights reserved.
	*
	* This software is licensed under terms that can be found in the LICENSE file
	* in the root directory of this software component.
	* If no LICENSE file comes with this software, it is provided AS-IS.
	*
	******************************************************************************
--]]

--// Libs
local libs = script.libs

--valve.src.__index.luau
return require(libs.constructor)